spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai?currentSchema=billing-system&ApplicationName=billing-system
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  ai:
    openai:
      api-key: sk-
      model: gpt-4
